"""
Epic 4.1 - Alembic migrations + PostgreSQL/PostGIS support.

The migration path is verified against SQLite (the tested default); the Postgres
branch is code-only until a PostGIS instance is available.
"""
from __future__ import annotations

from pathlib import Path

import pytest
from sqlalchemy import create_engine, inspect

_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def alembic_cfg(monkeypatch, tmp_path):
    from alembic.config import Config

    db = tmp_path / "mig.db"
    url = f"sqlite:///{db.as_posix()}"
    monkeypatch.setenv("DATABASE_URL", url)
    # settings is a cached singleton - patch it directly for this process
    from backend.core.config import settings
    monkeypatch.setattr(settings, "DATABASE_URL", url)

    cfg = Config(str(_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(_ROOT / "alembic"))
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg, url


def test_upgrade_head_builds_every_model_table(alembic_cfg):
    from alembic import command

    cfg, url = alembic_cfg
    command.upgrade(cfg, "head")

    import backend.models  # noqa: F401
    from backend.core.database import Base

    insp = inspect(create_engine(url))
    have = set(insp.get_table_names())
    want = set(Base.metadata.tables) | {"alembic_version"}
    assert want <= have, f"migration is missing tables: {want - have}"


def test_migrations_have_no_drift_from_the_models(alembic_cfg):
    from alembic import command
    from alembic.util.exc import AutogenerateDiffsDetected

    cfg, _ = alembic_cfg
    command.upgrade(cfg, "head")
    try:
        command.check(cfg)          # raises if the models diverge from head
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"alembic detected model/migration drift:\n{exc}")


def test_downgrade_base_drops_the_tables(alembic_cfg):
    from alembic import command

    cfg, url = alembic_cfg
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    insp = inspect(create_engine(url))
    remaining = set(insp.get_table_names()) - {"alembic_version"}
    assert not remaining, f"downgrade left tables behind: {remaining}"


def test_enable_postgis_is_a_noop_on_sqlite():
    from backend.core.database import enable_postgis
    assert enable_postgis() is False        # only acts on a postgres URL + geoalchemy2
