"""initial schema

Revision ID: 2904cd6359f2
Revises: 
Create Date: 2026-09-07 23:00:02.420494
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2904cd6359f2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('NATION', 'MARITIME_REGION', 'COASTAL_STATE', 'REGION', 'PORT', 'EEZ', 'ZONE', name='jurisdiction_type'), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['jurisdictions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jurisdictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jurisdictions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_jurisdictions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_jurisdictions_parent_id'), ['parent_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PILOT', 'REGIONAL', 'NATIONAL', name='user_role'), nullable=False),
    sa.Column('jurisdiction_ids', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmsi', sa.String(length=16), nullable=False),
    sa.Column('imo', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('call_sign', sa.String(length=16), nullable=True),
    sa.Column('flag', sa.String(length=64), nullable=True),
    sa.Column('vessel_type', sa.String(length=64), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vessels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vessels_mmsi'), ['mmsi'], unique=True)

    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ARCHIVED', name='investigation_status'), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('scene_ref', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('summary_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_jurisdiction_id'), ['jurisdiction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_reference'), ['reference'], unique=True)

    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('OIL_LIKE', 'AIS_BLACKOUT', 'SPEED_ANOMALY', 'COURSE_ANOMALY', 'ROUTE_DEVIATION', 'LOITERING', 'OTHER', name='anomaly_type'), nullable=False),
    sa.Column('source', sa.Enum('SAR', 'AIS_AUTOENCODER', 'TRAJECTORY_LSTM', 'HEURISTIC', 'FUSION', name='anomaly_source'), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomalies_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomalies_vessel_id'), ['vessel_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_id', sa.Integer(), nullable=True),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'WEBHOOK', name='alert_channel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'MOCKED', 'SUPPRESSED', name='alert_status'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_by_confidence', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('jurisdiction_codes', sa.JSON(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('time_bucket', sa.String(length=32), nullable=True),
    sa.Column('dedup_of_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dedup_of_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_anomaly_id'), ['anomaly_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_dedup_of_id'), ['dedup_of_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_recipient_user_id'), ['recipient_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_alerts_dedup_of_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_anomaly_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomalies_vessel_id'))
        batch_op.drop_index(batch_op.f('ix_anomalies_investigation_id'))

    op.drop_table('anomalies')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_reference'))
        batch_op.drop_index(batch_op.f('ix_investigations_jurisdiction_id'))
        batch_op.drop_index(batch_op.f('ix_investigations_created_by_id'))

    op.drop_table('investigations')
    with op.batch_alter_table('vessels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vessels_mmsi'))

    op.drop_table('vessels')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('jurisdictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jurisdictions_parent_id'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_name'))
        batch_op.drop_index(batch_op.f('ix_jurisdictions_code'))

    op.drop_table('jurisdictions')
    # ### end Alembic commands ###
